function out = simulate_linear_fullinfo_fixedgrid(sys, gains, cfg, tspan)
% Linear simulation with fixed output grid tspan (prevents memory blow-up).
% Control: u = -Kx + Ld, d=[d1; d2; d2dot], d1 is square wave, d2 generated by S.

A = sys.A; B = sys.B; P1 = sys.P1;
S = sys.S;
K = gains.K; Lgain = gains.L;

% initial augmented state z=[x; d]
d0 = [0; cfg.d2_0; cfg.d2dot_0];
z0 = [cfg.x0; d0];

ode = @(t,z) dyn(t,z);
opts = odeset('RelTol',1e-6,'AbsTol',1e-8);

% tspan is a vector -> solver returns values exactly on this grid
[t,z] = ode45(ode, tspan, z0, opts);

x = z(:,1:4).';
d = z(:,5:7).';

s   = x(1,:);
phi = x(3,:);
d2  = d(2,:);

e_s   = s - d2;
e_phi = phi;

out.t = t;
out.e_s = e_s;
out.e_phi = e_phi;

    function dz = dyn(t,z)
        x = z(1:4);
        d = z(5:7);

        d(1) = d1_square(t, cfg.d1_amp, cfg.d1_period); % imposed square wave
        u = -K*x + Lgain*d;

        xdot = A*x + B*u + P1*d(1);
        ddot = S*d;

        dz = [xdot; ddot];
    end
end
