function out = simulate_linear_fullinfo(sys, gains, cfg)
% SIMULATE_LINEAR_FULLINFO  (B2)
% Linear plant with full-information control:
%   u = -Kx + Ld
% d1(t) is the square wave; (d2,d2dot) generated by exosystem.

A = sys.A; B = sys.B; P1 = sys.P1;
C = sys.C; S = sys.S;
K = gains.K; Lgain = gains.L;

% initial conditions
d0 = [0; cfg.d2_0; cfg.d2dot_0];  % d1 overwritten anyway
z0 = [cfg.x0; d0];

ode = @(t,z) dyn(t,z);
opts = odeset('RelTol',1e-7,'AbsTol',1e-9);
[t,z] = ode45(ode, [0 cfg.tEnd], z0, opts);

x = z(:,1:4).';
d = z(:,5:7).';

y  = C*x;
u  = zeros(1,numel(t));
d2 = d(2,:);

for k = 1:numel(t)
    u(k) = -K*x(:,k) + Lgain*d(:,k);
end

out.t = t;
out.y = y;
out.u = u;
out.d2 = d2;

    function dz = dyn(t,z)
        x = z(1:4);
        d = z(5:7);

        % enforce square-wave disturbance
        d(1) = d1_square(t, cfg.d1_amp, cfg.d1_period);

        u = -K*x + Lgain*d;

        % plant: xdot = A x + B u + P1 d1
        xdot = A*x + B*u + P1*d(1);

        % exosystem for (d2,d2dot)
        ddot = S*d;

        dz = [xdot; ddot];
    end
end
